### ISSUE TITLE
TinyMCE Advanced - Stop removing p and br tags issue

### ISSUE THREAD

**Issue by onetrev** [Viper007Bond/syntaxhighlighter#24]
From my testing, I seem to have a major issue when combining Syntax Highlighter and TinyMCE Advanced with this option turned on:

"Stop removing the `<p>` and `<br />` tags when saving and show them in the HTML editor" 

When I have this option on, and I re-save a post using this Syntax Highlighter the code gets 100% mangled with `<br />` tags all over the place. Having this options is super handy in my experience with the WP HTML editor, so any ideas how these two can be combined?

Thanks!

**Comment by Viper007Bond** [comment]
It's unlikely there is a workaround. Enabling that option sounds like it's saving `<p>` and `<br />` tags into the actual post content rather than letting WordPress add them during output of the post where they can be more efficiently added, i.e. after my plugin has done it's thing. WordPress is smart enough to not add them inside of `<pre>` tags (which my shortcodes turn into).

I think you're going to just need to leave that option disabled, which I would recommend regardless otherwise you're going to break more than just my plugin.

PS: Please use [the WordPress.org support forums](http://wordpress.org/support/plugin/syntaxhighlighter) for support questions. Just bug reports here on GitHub. :)
