### ISSUE TITLE
do_shortcode($post_meta_field) returns 1 for each shortcode

### ISSUE THREAD

**Issue by riconeitzel** [Viper007Bond/syntaxhighlighter#25]
If you use 

```
echo do_shortcode(get_post_meta('fieldname', $post->ID, true));
```

you'll get your shortcodes and their content returned as '1'
## Example

```
$content_from_a_post_meta_field = '
This is an 
[php]$example_demonstration = true[/php]
for your convenience';

echo do_shortcode($content_from_a_post_meta_field);
```

returns "This is an 1 for your convenience"

**Comment by Viper007Bond** [comment]
You need to do this instead:

`echo apply_filters( 'the_content', $content_from_a_post_meta_field );`

This plugin doesn't process its shortcodes in the traditional way in order to avoid other filters messing up the code.

See http://www.viper007bond.com/2009/11/22/wordpress-code-earlier-shortcodes/
